"""
CBLS-38 prototype: rubric + feedback -> mastery estimate per learning outcome.

Built against the CBLS-40 contract (finalised by Su, see CBLS40.md in the repo).

Design note: student_id, subject_code, learning_outcome, competency, and the
evidence fields (rubric_level, feedback) are already present in the input, so
they are passed through directly rather than regenerated by the model - this
avoids the model subtly rephrasing text it was already given, and only asks
it to judge the two fields that actually require reasoning:
mastery_estimate and identified_gap.
"""

import json
import os
from anthropic import Anthropic

# ---------------------------------------------------------------------------
# CBLS-40 CONTRACT
# ---------------------------------------------------------------------------
INPUT_FIELDS = {
    "student_id": int,
    "subject_code": str,
    "assignment": str,
    "competency": str,
    "learning_outcome": str,
    "rubric_criterion": str,
    "rubric_level": str,
    "feedback": str,
}

# Fields the MODEL must produce (only the two that require judgment)
MODEL_OUTPUT_FIELDS = {
    "mastery_estimate": str,   # "Not Yet Achieved" / "Partially Achieved" / "Achieved"
    "identified_gap": str,     # short phrase describing the gap, or "" if none
}

VALID_MASTERY_LEVELS = {"Not Yet Achieved", "Partially Achieved", "Achieved"}
VALID_RUBRIC_LEVELS = {"Weak", "Adequate", "Strong"}

MODEL_OUTPUT_DESCRIPTION = """
Return ONLY a JSON object, no other text, with exactly these two fields:
- "mastery_estimate": one of "Not Yet Achieved", "Partially Achieved", or "Achieved"
- "identified_gap": a short phrase describing the specific gap in this
  student's understanding (empty string "" if mastery_estimate is "Achieved"
  with no notable gap)
"""
# ---------------------------------------------------------------------------


def validate_input(record: dict) -> None:
    """Validate an input record against the CBLS-40 input contract."""
    for field, expected_type in INPUT_FIELDS.items():
        if field not in record:
            raise ValueError(f"Input missing field '{field}': {record}")
        if not isinstance(record[field], expected_type):
            raise ValueError(
                f"Input field '{field}' has wrong type: {record[field]!r}"
            )
    if record["rubric_level"] not in VALID_RUBRIC_LEVELS:
        raise ValueError(
            f"Input field 'rubric_level' must be one of {VALID_RUBRIC_LEVELS}, "
            f"got: {record['rubric_level']!r}"
        )


def build_prompt(record: dict) -> str:
    """Construct the prompt sent to the model for a single input record."""
    return f"""You are analysing marked student feedback against a rubric to
estimate mastery of a specific learning outcome.

Competency: {record['competency']}
Learning outcome: {record['learning_outcome']}
Rubric criterion: {record['rubric_criterion']}
Rubric level awarded: {record['rubric_level']}
Feedback given: {record['feedback']}

{MODEL_OUTPUT_DESCRIPTION}
"""


def call_model(prompt: str) -> str:
    """Send the prompt to the model and return the raw text response."""
    client = Anthropic()  # reads ANTHROPIC_API_KEY from env
    response = client.messages.create(
        model="claude-sonnet-4-5",  # check docs.claude.com for the current model string
        max_tokens=512,
        messages=[{"role": "user", "content": prompt}],
    )
    return "".join(
        block.text for block in response.content if block.type == "text"
    )


def strip_code_fences(raw_text: str) -> str:
    """Strip markdown code fences if the model wrapped its JSON in them."""
    cleaned = raw_text.strip()
    if cleaned.startswith("```"):
        cleaned = cleaned.split("\n", 1)[1] if "\n" in cleaned else cleaned
        if cleaned.rstrip().endswith("```"):
            cleaned = cleaned.rstrip()[:-3]
    return cleaned.strip()


def parse_model_output(raw_text: str) -> dict:
    """Parse and validate the model's judgment fields against the contract."""
    cleaned = strip_code_fences(raw_text)

    try:
        data = json.loads(cleaned)
    except json.JSONDecodeError as e:
        raise ValueError(f"Model output was not valid JSON: {e}\nRaw: {raw_text}")

    for field, expected_type in MODEL_OUTPUT_FIELDS.items():
        if field not in data:
            raise ValueError(f"Model output missing field '{field}': {data}")
        if not isinstance(data[field], expected_type):
            raise ValueError(
                f"Model output field '{field}' has wrong type: {data[field]!r}"
            )
    if data["mastery_estimate"] not in VALID_MASTERY_LEVELS:
        raise ValueError(
            f"Model output 'mastery_estimate' must be one of "
            f"{VALID_MASTERY_LEVELS}, got: {data['mastery_estimate']!r}"
        )

    return data


def estimate_mastery(record: dict) -> dict:
    """
    Main entry point: one CBLS-40 input record -> one CBLS-40 output record.

    Pass-through fields (student_id, subject_code, learning_outcome,
    competency, evidence.rubric_level, evidence.feedback) are taken directly
    from the input. Only mastery_estimate and identified_gap come from the
    model.
    """
    validate_input(record)

    prompt = build_prompt(record)
    raw_output = call_model(prompt)
    model_output = parse_model_output(raw_output)

    return {
        "student_id": record["student_id"],
        "subject_code": record["subject_code"],
        "learning_outcome": record["learning_outcome"],
        "competency": record["competency"],
        "mastery_estimate": model_output["mastery_estimate"],
        "identified_gap": model_output["identified_gap"],
        "evidence": {
            "rubric_level": record["rubric_level"],
            "feedback": record["feedback"],
        },
    }


if __name__ == "__main__":
    # Example matching the CBLS-40 contract exactly.
    # Swap this out for your CBLS-39 synthetic samples.
    example_input = {
        "student_id": 3,
        "subject_code": "CSE1DBS",
        "assignment": "CSE1DBS Assignment 1",
        "competency": "Technical Implementation",
        "learning_outcome": "CSE1DBS-LO1",
        "rubric_criterion": "Query Design & Normalization",
        "rubric_level": "Adequate",
        "feedback": "[Technical Implementation] The solution is mostly correct but needs stronger technical detail.",
    }

    result = estimate_mastery(example_input)
    print(json.dumps(result, indent=2))
